security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        api_user_provider:
            id: api_user.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/(?!api)
            security: false
        api_public:
            pattern: ^/api/public
            security: false
        api_doc:
            pattern: ^/api/doc
            security: false
        api:
            pattern: ^/api
            provider: api_user_provider
            guard:
                authenticators:
                    - username_password.authenticator

    access_control:
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/api, roles: ROLE_NO_ACCESS }
