security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\User:
            algorithm: bcrypt

    providers:
        api_doc_provider:
            memory:
                users:
                    admin:
                        password: admin
                        roles: ROLE_ADMIN
        api_user_provider:
            id: api_user.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/(?!api)
            security: false
        api_doc:
            pattern: ^/api/doc
            provider: api_doc_provider
            http_basic: ~
#            security: false
        api:
            pattern: ^/api
            provider: api_user_provider
            guard:
                authenticators:
                    - username_password.authenticator
            anonymous: true
            logout:
                path: /api/security/logout

    access_control:
        - { path: ^/api/public, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/api, roles: ROLE_NO_ACCESS }
